magephp:
    environments:
        production:
            user: root
            branch: master
            from: ./
            host_path: /var/www/html
            exclude:
                - ./app/config/parameters.yml
                - ./var/cache/*
                - ./var/log/*
                - ./web/app_dev.php
            hosts:
                - 90.61.28.217
            pre-deploy:
                - git/update
                - composer/install
                - composer/dump-autoload
            on-deploy:
            on-release:
            post-release:
            post-deploy:
                - symfony/cache-warmup
                - symfony/assets-install
                - symfony/cache-clear